import { createFileRoute, Link } from "@tanstack/react-router";
import { Reveal } from "@/components/storefront/reveal";
import { ABOUT } from "@/lib/store/about-content";

export const Route = createFileRoute("/about")({ component: AboutPage });

function AboutPage() {
  return <main>
    <section className="border-b border-border px-5 pb-20 pt-20 md:px-10 md:pb-28 md:pt-28">
      <Reveal className="max-w-5xl"><p className="text-[11px] uppercase tracking-[0.28em] text-muted-foreground">{ABOUT.qualifier}</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-0.05em] md:text-7xl">{ABOUT.name}</h1><p className="mt-7 max-w-2xl text-lg font-light leading-relaxed text-muted-foreground">{ABOUT.tagline}</p><p className="mt-8 max-w-3xl text-xl font-light leading-relaxed">{ABOUT.positioning}</p></Reveal>
    </section>

    <section className="grid gap-10 px-5 py-20 md:grid-cols-[minmax(0,1fr)_minmax(320px,0.72fr)] md:items-start md:px-10 md:py-28">
      <Reveal><p className="text-[11px] uppercase tracking-[0.28em] text-muted-foreground">Our story</p><h2 className="mt-4 max-w-2xl text-4xl font-medium tracking-tight md:text-6xl">Time, looked after.</h2>{ABOUT.about.map((paragraph) => <p key={paragraph} className="mt-7 max-w-2xl text-base font-light leading-relaxed text-muted-foreground">{paragraph}</p>)}</Reveal>
      <Reveal className="rounded-2xl bg-card p-7 ring-1 ring-foreground/8 md:p-9"><p className="text-[11px] uppercase tracking-[0.22em] text-muted-foreground">Our promise</p><p className="mt-6 text-2xl font-light leading-relaxed">Authentic timepieces. Genuine service. A relationship that lasts beyond the sale.</p><div className="mt-10 grid grid-cols-2 gap-6 border-t border-border pt-6"><div><p className="text-3xl font-medium">1981</p><p className="mt-1 text-xs uppercase tracking-[0.16em] text-muted-foreground">Founded in Delhi</p></div><div><p className="text-3xl font-medium">40+</p><p className="mt-1 text-xs uppercase tracking-[0.16em] text-muted-foreground">Years of heritage</p></div></div></Reveal>
    </section>

    <section className="bg-card px-5 py-20 md:px-10 md:py-28"><Reveal><div className="mb-12 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-[11px] uppercase tracking-[0.28em] text-muted-foreground">Ownership & leadership</p><h2 className="mt-4 text-4xl font-medium tracking-tight md:text-5xl">A family business, carried forward.</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">The people and principles behind Sahil Watch Company.</p></div><div className="grid gap-10 lg:grid-cols-[minmax(230px,280px)_minmax(0,1fr)_minmax(0,1fr)]"><div className="w-full max-w-[280px] overflow-hidden rounded-2xl bg-background"><img src="/about/founder-portrait-placeholder.svg" alt="Founder portrait placeholder for Mr. Parveen Kapoor" className="aspect-video w-full object-cover" /><p className="p-4 text-[10px] uppercase tracking-[0.16em] text-muted-foreground">Founder portrait · 16:9</p></div><div><p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">{ABOUT.founder.role}</p><h3 className="mt-3 text-2xl font-medium">{ABOUT.founder.name}</h3><p className="mt-5 text-base font-light leading-relaxed text-muted-foreground">{ABOUT.founder.bio}</p></div><div><p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">{ABOUT.owner.role}</p><h3 className="mt-3 text-2xl font-medium">{ABOUT.owner.name}</h3><p className="mt-5 text-base font-light leading-relaxed text-muted-foreground">{ABOUT.owner.bio}</p></div></div></Reveal></section>

    <section className="px-5 py-20 md:px-10 md:py-28"><Reveal><p className="text-[11px] uppercase tracking-[0.28em] text-muted-foreground">Our values</p><h2 className="mt-4 max-w-3xl text-4xl font-medium tracking-tight md:text-5xl">The principles that keep us on time.</h2><div className="mt-14 grid gap-10 md:grid-cols-3">{ABOUT.values.map(([number, title, description]) => <article key={number} className="border-t border-border pt-5"><p className="text-sm text-muted-foreground">{number}</p><h3 className="mt-7 text-xl font-medium leading-snug">{title}</h3><p className="mt-4 text-sm font-light leading-relaxed text-muted-foreground">{description}</p></article>)}</div></Reveal></section>

    <section className="bg-primary px-5 py-20 text-primary-foreground md:px-10 md:py-28"><Reveal><p className="text-[11px] uppercase tracking-[0.28em] text-primary-foreground/65">Services & offerings</p><h2 className="mt-4 max-w-3xl text-4xl font-medium tracking-tight md:text-5xl">Everything your timepiece deserves.</h2><div className="mt-14 grid gap-8 md:grid-cols-3">{ABOUT.services.map(([title, description]) => <article key={title} className="border-t border-primary-foreground/20 pt-5"><h3 className="text-xl font-medium">{title}</h3><p className="mt-4 text-sm font-light leading-relaxed text-primary-foreground/70">{description}</p></article>)}</div></Reveal></section>

    <section className="grid gap-12 px-5 py-20 md:grid-cols-2 md:px-10 md:py-28"><Reveal><p className="text-[11px] uppercase tracking-[0.28em] text-muted-foreground">Visit us</p><h2 className="mt-4 text-4xl font-medium tracking-tight md:text-5xl">Come by the store.</h2><div className="mt-9 space-y-6 text-sm leading-relaxed"><div><p className="font-medium">Showroom</p>{ABOUT.contact.showroom.map((line) => <p key={line} className="text-muted-foreground">{line}</p>)}</div><div><p className="font-medium">Area address</p><p className="text-muted-foreground">{ABOUT.contact.area}</p></div><div><p className="font-medium">Call & WhatsApp</p>{ABOUT.contact.phones.map((phone) => <div key={phone} className="mt-2 flex flex-wrap gap-x-4 gap-y-1"><a href={`tel:${phone.replaceAll(" ", "")}`} className="text-muted-foreground underline-offset-4 hover:underline">Call {phone}</a><a href={`https://wa.me/${phone.replaceAll("+", "").replaceAll(" ", "")}`} className="text-muted-foreground underline-offset-4 hover:underline">WhatsApp {phone}</a></div>)}<p className="mt-2 text-xs text-muted-foreground">{ABOUT.contact.whatsappNote}</p></div><a href={ABOUT.contact.instagramUrl} className="inline-block underline-offset-4 hover:underline">Instagram {ABOUT.contact.instagramLabel}</a></div></Reveal><Reveal className="rounded-2xl bg-card p-7 ring-1 ring-foreground/8 md:p-9"><p className="text-[11px] uppercase tracking-[0.22em] text-muted-foreground">Opening hours</p><div className="mt-7 divide-y divide-border">{ABOUT.timings.map(([day, hours]) => <div key={day} className="flex justify-between gap-6 py-3 text-sm"><span>{day}</span><span className={hours === "Closed" ? "text-destructive" : "text-muted-foreground"}>{hours}</span></div>)}</div><p className="mt-6 text-xs leading-relaxed text-muted-foreground">Open six days a week. Closed on Wednesdays.</p></Reveal></section>

    <section className="border-t border-border px-5 py-16 md:px-10 md:py-20"><Reveal><p className="text-[11px] uppercase tracking-[0.28em] text-muted-foreground">Quick facts</p><div className="mt-8 flex flex-wrap gap-3">{ABOUT.quickFacts.map((fact) => <span key={fact} className="rounded-full border border-border px-4 py-2 text-sm text-muted-foreground">{fact}</span>)}</div></Reveal></section>
    <section className="px-5 pb-24 text-center md:px-10 md:pb-32"><Reveal><p className="text-[11px] uppercase tracking-[0.28em] text-muted-foreground">The collection</p><h2 className="mt-4 text-4xl font-medium tracking-tight md:text-5xl">Find a watch worth keeping.</h2><Link to="/watches" className="mt-8 inline-flex h-12 items-center rounded-lg bg-primary px-6 text-sm font-medium text-primary-foreground">Explore watches</Link></Reveal></section>
  </main>;
}
