import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useAdminDialog } from "@/components/admin/admin-dialog";
import { AdminLayout } from "@/components/admin/admin-layout";
import { AdminFormField, AdminPage, AdminState, ProductForm, type ProductFormValue } from "@/components/admin/admin-utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { adminCreateProduct, adminDeleteProduct, adminListBrands, adminListProducts, adminUpdateProduct, adminUpdateStock } from "@/lib/store/admin";
import type { Brand, Product } from "@/lib/store/types";
import { formatInr } from "@/lib/store/format";
export const Route = createFileRoute("/admin/products")({ component: AdminProductsPage });
function AdminProductsPage() {
  const { alert, confirm, prompt } = useAdminDialog();
  const [products, setProducts] = useState<Product[]>([]); const [brands, setBrands] = useState<Brand[]>([]); const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Product | null>(null); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>(null);
  async function load() { setLoading(true); try { const [nextProducts, nextBrands] = await Promise.all([adminListProducts({ data: { search } }), adminListBrands()]); setProducts(nextProducts); setBrands(nextBrands); setError(null); } catch (e) { setError(e); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function save(value: ProductFormValue) { if (!value.name.trim() || !value.shortDescription.trim() || !value.fullDescription.trim() || !value.brandId || value.price < 1 || value.stock < 1) { await alert({ title: "Required Information", description: "Please complete the product name, brand, descriptions, price, and stock before continuing." }); return; } try { if (editing) await adminUpdateProduct({ data: { ...value, id: editing.id } }); else await adminCreateProduct({ data: value }); await alert({ title: editing ? "Product updated" : "Product added", description: editing ? "The product details were updated successfully." : "The product was added successfully." }); setEditing(null); setCreating(false); await load(); } catch (e) { await alert({ title: editing ? "Product update failed" : "Product creation failed", description: e instanceof Error ? e.message : "Something went wrong. Please try again." }); } }
  async function remove(product: Product) { if (!await confirm({ title: "Delete product?", description: `You are about to permanently delete ${product.name}. This action cannot be undone.`, confirmLabel: "Delete product", cancelLabel: "Keep product", destructive: true })) return; try { await adminDeleteProduct({ data: { id: product.id } }); await alert({ title: "Product deleted", description: "The product was deleted successfully." }); await load(); } catch (e) { await alert({ title: "Product deletion failed", description: e instanceof Error ? e.message : "Something went wrong. Please try again." }); } }
  async function stock(product: Product) { const raw = await prompt({ title: "Update stock", description: `Set the current stock quantity for ${product.name}. Enter a whole number from 1 to 1000.`, confirmLabel: "Update stock", cancelLabel: "Cancel", input: { label: "Stock quantity", defaultValue: String(product.stock), type: "number" } }); if (raw === null) return; const next = Number(raw); if (!Number.isInteger(next) || next < 1 || next > 1000) { await alert({ title: "Required Information", description: "Please enter a whole number from 1 to 1000 before continuing." }); return; } try { await adminUpdateStock({ data: { id: product.id, stock: next } }); await alert({ title: "Stock updated", description: "The stock quantity was updated successfully." }); await load(); } catch (e) { await alert({ title: "Stock update failed", description: e instanceof Error ? e.message : "Something went wrong. Please try again." }); } }
  if (creating || editing) return <AdminLayout><AdminPage title={editing ? "Edit product" : "New product"}><div className="w-full max-w-3xl rounded-2xl border border-border bg-card p-4 sm:p-6"><ProductForm initial={editing ? { ...editing, videoUrl: editing.videoUrl ?? "", videoPosterUrl: editing.videoPosterUrl ?? "" } : undefined} brands={brands} onSubmit={save} onCancel={() => { setCreating(false); setEditing(null); }} /></div></AdminPage></AdminLayout>;
  return <AdminLayout><AdminPage title="Products"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="min-w-0 flex-1"><AdminFormField label="Search"><Input className="bg-background text-foreground placeholder:text-muted-foreground" value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") void load(); }} placeholder="Search products or brands…" /></AdminFormField></div><Button className="shrink-0" onClick={() => setCreating(true)}>Add product</Button></div><AdminState loading={loading} error={error}><div className="overflow-hidden rounded-2xl border border-border bg-card"><div className="hidden grid-cols-[60px_1fr_110px_120px_100px_150px] gap-4 border-b border-border px-5 py-3 text-xs uppercase tracking-[0.16em] text-muted-foreground md:grid"><span>Image</span><span>Product</span><span>Collection</span><span>Price</span><span>Stock</span><span>Actions</span></div>{products.map((p) => <div key={p.id} className="grid gap-3 border-b border-border px-5 py-4 last:border-0 md:grid-cols-[60px_1fr_110px_120px_100px_150px] md:items-center md:gap-4"><img src={p.images[0] ?? ""} alt={p.name} className="size-12 rounded-lg bg-muted object-contain object-center" /><div><p className="font-medium">{p.name}</p><p className="text-sm text-muted-foreground">{p.brandName} · {p.shortDescription}</p></div><span className="text-sm capitalize text-muted-foreground">{p.collection}</span><span className="text-sm">{formatInr(p.sellingPrice)}</span><span className={p.stock < 8 ? "text-sm text-destructive" : "text-sm"}>{p.stock} units{p.stock < 8 ? " · Low" : " · Live"}</span><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => setEditing(p)}>Edit</Button><Button size="sm" variant="secondary" onClick={() => void stock(p)}>Stock</Button><Button size="sm" variant="ghost" onClick={() => void remove(p)}>Delete</Button></div></div>)}{products.length === 0 ? <p className="p-6 text-sm text-muted-foreground">No products found.</p> : null}</div></AdminState></AdminPage></AdminLayout>;
}
