import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AdminLayout } from "@/components/admin/admin-layout";
import { AdminPage, formatInr } from "@/components/admin/admin-utils";
import { getAdminOverview } from "@/lib/store/admin";
import type { AdminOverview } from "@/lib/store/types";
export const Route = createFileRoute("/admin/")({ component: AdminPageRoute });
function AdminPageRoute() {
  const [overview, setOverview] = useState<AdminOverview | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>(null);
  useEffect(() => { void getAdminOverview().then(setOverview).catch(setError).finally(() => setLoading(false)); }, []);
  return <AdminLayout><AdminPage title="Overview" kicker="Overview">{loading ? <p className="rounded-xl border border-border p-6 text-sm text-muted-foreground">Loading overview…</p> : error || !overview ? <p className="rounded-xl border border-destructive/30 p-6 text-sm text-destructive">Could not load the overview.</p> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Live products" value={overview.liveProducts} /><Metric label="Total orders" value={overview.totalOrders} /><Metric label="Revenue before refunds" value={formatInr(overview.revenue)} /><Metric label="Low stock" value={overview.lowStockCount} /></div><div className="flex flex-wrap gap-3"><Link className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground" to="/admin/products">Manage products</Link><Link className="rounded-md border border-border px-4 py-2 text-sm" to="/admin/orders">Review orders</Link><a className="rounded-md border border-border px-4 py-2 text-sm" href="/">View store</a></div><section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border p-6"><h2 className="text-lg font-medium">Inventory at a glance</h2><p className="mt-1 text-sm text-muted-foreground">Low stock means fewer than 8 units remaining.</p></div><div className="divide-y divide-border">{overview.inventory.map((item) => <div key={item.id} className="grid gap-2 px-6 py-4 text-sm sm:grid-cols-[1fr_100px_120px_140px] sm:items-center"><span className="font-medium">{item.name}</span><span className="capitalize text-muted-foreground">{item.collection}</span><span className={item.stock < 8 ? "text-destructive" : "text-muted-foreground"}>{item.stock} in stock</span><span className="text-muted-foreground">{formatInr(item.sellingPrice)}</span></div>)}</div></section></>}</AdminPage></AdminLayout>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></div>; }
